[package]
name = "slack"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.1"
base64 = "0.22.1"
dotenvy = "0.15.7"
hyper = "1.6.0"
reqwest = {version= "0.12.12",features = ["json"]}
serde = { version = "1.0.218", features = ["derive"]}
serde_json = "1.0.140"
thiserror = "2.0.12"
tokio = { version="1.44.0",features = ["macros","rt-multi-thread"]}
tower-http = "0.6.2"
tracing = "0.1.41"
tracing-subscriber = {version = "0.3.19" , features = ["json","env-filter"]}
