name: Build and Push to Harbor - hitomi

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

env:
  HARBOR_URL: 192.168.122.100:80
  HARBOR_PROJECT: sandbox
  HARBOR_USERNAME: admin
  REPOSITORY_NAME: hitomi

jobs:
  build-and-push:
    runs-on: hitomi-runners
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker
      run: |
        echo "=== Docker環境確認 ==="
        docker --version
        docker info || true
        
    - name: Build Docker image
      run: |
        echo "=== Building Docker image ==="
        echo "📦 Building from Dockerfile..."
        docker build -t hitomi:latest .
        docker tag hitomi:latest hitomi:${{ github.sha }}
        echo "✅ Docker image built successfully"
        docker images | grep hitomi || true
        
    - name: Save Docker images
      run: |
        echo "=== Saving Docker images to tar ==="
        docker save hitomi:latest -o /tmp/hitomi-latest.tar
        docker save hitomi:${{ github.sha }} -o /tmp/hitomi-sha.tar
        ls -lh /tmp/*.tar
        echo "✅ Images saved successfully"
        
    - name: Setup Harbor credentials
      run: |
        echo "=== Setting up Harbor connection ==="
        
        # Harbor認証情報取得
        kubectl get secret harbor-credentials -n default -o jsonpath='{.data.password}' | base64 -d > /tmp/harbor_password || echo "Harbor12345" > /tmp/harbor_password
        
        # Harbor接続確認
        echo "Testing Harbor connectivity..."
        curl -k -f -s -o /dev/null -w "%{http_code}" "http://$HARBOR_URL/api/v2.0/systeminfo" || echo "Harbor connection test: HTTP $?"
        
        echo "✅ Harbor credentials configured"
        
    - name: Push to Harbor using skopeo
      run: |
        echo "=== Pushing to Harbor with skopeo ==="
        
        # skopeoインストール確認
        if ! command -v skopeo &> /dev/null; then
          echo "Installing skopeo..."
          sudo apt-get update && sudo apt-get install -y skopeo
        fi
        
        HARBOR_PASSWORD=$(cat /tmp/harbor_password)
        
        # TLS検証を無効化してHarborにpush
        echo "Pushing hitomi:latest to Harbor..."
        skopeo copy --insecure-policy --dest-tls-verify=false \
          --dest-creds="$HARBOR_USERNAME:$HARBOR_PASSWORD" \
          docker-archive:/tmp/hitomi-latest.tar \
          docker://harbor.local/$HARBOR_PROJECT/hitomi:latest
        
        echo "Pushing hitomi:${{ github.sha }} to Harbor..."
        skopeo copy --insecure-policy --dest-tls-verify=false \
          --dest-creds="$HARBOR_USERNAME:$HARBOR_PASSWORD" \
          docker-archive:/tmp/hitomi-sha.tar \
          docker://harbor.local/$HARBOR_PROJECT/hitomi:${{ github.sha }}
        
        echo "✅ Images pushed successfully to Harbor"
        
    - name: Cleanup
      if: always()
      run: |
        echo "=== Cleanup ==="
        rm -f /tmp/harbor_* /tmp/kubeconfig /tmp/hitomi-*.tar
        echo "✅ Cleanup completed"
