name: Harborへのビルドとプッシュ

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: slack-rs-runners  # Runner Scale Set名
    
    steps:
    - name: コードをチェックアウト
      uses: actions/checkout@v4
      
    - name: Harbor証明書の信頼確認
      run: |
        # Harbor証明書が信頼されているか確認（Harbor CA Trust DaemonSetで処理済み）
        echo "Harbor証明書の信頼状態を確認中..."
        docker info | grep -i "insecure" || echo "非セキュアレジストリの設定なし（期待される状態）"
        
        # Harbor接続テスト（オプション）
        curl -f https://192.168.122.100/api/v2.0/systeminfo || echo "Harbor接続テスト失敗、docker loginを続行"
        
    - name: Harborにログイン
      run: |
        # Docker daemonの非セキュアレジストリ設定
        sudo mkdir -p /etc/docker
        echo '{"insecure-registries": ["192.168.122.100"]}' | sudo tee /etc/docker/daemon.json
        sudo systemctl restart docker
        sleep 5
        
        # Harbor証明書を無視してログイン
        echo "Harbor12345" | docker login 192.168.122.100 -u admin --password-stdin
        
    - name: Dockerイメージのビルドとプッシュ
      run: |
        docker build -t 192.168.122.100/sandbox/${{ github.event.repository.name }}:latest .
        docker push 192.168.122.100/sandbox/${{ github.event.repository.name }}:latest
        
    - name: Trivyによるイメージスキャン
      uses: aquasecurity/trivy-action@master
      if: github.event_name != 'pull_request'
      with:
        image-ref: 192.168.122.100/sandbox/${{ github.event.repository.name }}:latest
        format: 'sarif'
        output: 'trivy-results.sarif'
        
    - name: Trivyスキャン結果のアップロード
      uses: github/codeql-action/upload-sarif@v2
      if: always() && github.event_name != 'pull_request'
      with:
        sarif_file: 'trivy-results.sarif'
