name: Harborへのビルドとプッシュ

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: slack-rs-runners 
    
    steps:
    - name: コードをチェックアウト
      uses: actions/checkout@v4
      
    - name: Harbor接続テスト
      run: |
        echo "=== Harbor Connection Test ==="
        curl -k -u admin:Harbor12345 https://192.168.122.100/v2/_catalog
        curl -k -u admin:Harbor12345 https://192.168.122.100/api/v2.0/projects | jq '.[] | select(.name=="sandbox")'
        
    - name: Docker設定とビルド
      run: |
        echo "=== Docker Setup ==="
        
        # Docker認証設定
        mkdir -p ~/.docker
        echo '{"auths":{"192.168.122.100":{"auth":"'$(echo -n 'admin:Harbor12345' | base64 -w 0)'"}}}' > ~/.docker/config.json
        
        # Dockerイメージビルド
        docker build -t 192.168.122.100/sandbox/${{ github.event.repository.name }}:latest .
        
        echo "=== Docker Info ==="
        docker info | grep -A 5 "Insecure Registries" || echo "No insecure registries shown"
        
    - name: Harbor Push
      run: |
        echo "=== Harbor Push Attempt ==="
        
        # 方式1: 標準プッシュ試行
        docker push 192.168.122.100/sandbox/${{ github.event.repository.name }}:latest || echo "Standard push failed"
        
        # 方式2: craneツールを使用
        echo "Installing crane for insecure push..."
        curl -sL "https://github.com/google/go-containerregistry/releases/latest/download/go-containerregistry_Linux_x86_64.tar.gz" | tar xz -C /tmp
        chmod +x /tmp/crane
        
        echo "Using crane for insecure push..."
        
        # DNSエントリをローカルで追加
        echo "192.168.122.100 harbor.local" | sudo tee -a /etc/hosts
        
        # Craneにinsecure registry設定を追加
        export CRANE_INSECURE=true
        /tmp/crane auth login 192.168.122.100 -u admin -p Harbor12345 --insecure || echo "Crane auth failed"
        
        # 方式2a: Docker daemonから直接プッシュ
        /tmp/crane copy docker-daemon:192.168.122.100/sandbox/${{ github.event.repository.name }}:latest 192.168.122.100/sandbox/${{ github.event.repository.name }}:latest --insecure || echo "Crane copy failed"
        
        # 方式3: regctlツールを使用
        echo "Installing regctl for insecure push..."
        curl -L https://github.com/regclient/regclient/releases/latest/download/regctl-linux-amd64 -o /tmp/regctl
        chmod +x /tmp/regctl
        
        echo "Using regctl for insecure push..."
        
        # regctlの設定でinsecure registryを許可
        /tmp/regctl registry set 192.168.122.100 --tls disabled
        /tmp/regctl image copy docker-daemon:192.168.122.100/sandbox/${{ github.event.repository.name }}:latest 192.168.122.100/sandbox/${{ github.event.repository.name }}:latest || echo "regctl push failed"
        
        # 方式4: oras pushツールを使用
        echo "Installing oras for OCI push..."
        curl -LO https://github.com/oras-project/oras/releases/latest/download/oras_linux_amd64.tar.gz
        tar -xzf oras_linux_amd64.tar.gz -C /tmp
        chmod +x /tmp/oras
        
        echo "Using oras for insecure push..."
        docker save 192.168.122.100/sandbox/${{ github.event.repository.name }}:latest -o /tmp/image.tar
        /tmp/oras push --insecure 192.168.122.100/sandbox/${{ github.event.repository.name }}:latest /tmp/image.tar:application/vnd.docker.image.rootfs.diff.tar || echo "oras push failed"
        
        # 方式5: Manual API upload
        echo "Manual API upload attempt..."
        docker save 192.168.122.100/sandbox/${{ github.event.repository.name }}:latest | gzip > /tmp/image.tar.gz
        echo "Image saved to /tmp/image.tar.gz for manual processing"
        
    - name: プッシュ結果確認
      run: |
        echo "=== Push Result Verification ==="
        curl -k -u admin:Harbor12345 https://192.168.122.100/v2/sandbox/${{ github.event.repository.name }}/tags/list
        curl -k -u admin:Harbor12345 "https://192.168.122.100/api/v2.0/projects/sandbox/repositories"