name: Build and Push to Harbor

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: slack-rs-runners  # ← Runner Scale Set名に変更

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup Docker insecure registry
        run: |
          # Dockerd設定でinsecure registryを許可
          sudo mkdir -p /etc/docker
          echo '{"insecure-registries":["192.168.122.100"]}' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker || sudo service docker restart
          sleep 10

      - name: Login to Harbor
        run: |
          echo "Harbor12345" | docker login 192.168.122.100 -u admin --password-stdin

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: 192.168.122.100/sandbox/${{ github.event.repository.name }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
