name: Harborへのビルドとプッシュ

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: slack-rs-runners 
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Harbor接続確認
      run: |
        echo "=== Harbor API Connection Test ==="
        echo "HARBOR_USERNAME: $HARBOR_USERNAME"
        echo "HARBOR_PASSWORD: ${HARBOR_PASSWORD:0:5}..."
        curl -k -u $HARBOR_USERNAME:$HARBOR_PASSWORD https://192.168.122.100/v2/_catalog
        curl -k -u $HARBOR_USERNAME:$HARBOR_PASSWORD https://192.168.122.100/api/v2.0/projects | jq '.[] | select(.name=="sandbox")'
        
    - name: Dockerイメージビルド
      run: |
        echo "=== Docker Image Build ==="
        
        # Docker認証設定
        mkdir -p ~/.docker
        echo '{"auths":{"192.168.122.100":{"auth":"'$(echo -n \"$HARBOR_USERNAME:$HARBOR_PASSWORD\" | base64 -w 0)'"}}}' > ~/.docker/config.json
        
        # Dockerイメージビルド
        docker build -t 192.168.122.100/sandbox/${{ github.event.repository.name }}:latest .
        docker build -t 192.168.122.100/sandbox/${{ github.event.repository.name }}:${{ github.sha }} .
        
    - name: Harborプッシュ（crane使用）
      run: |
        echo "=== Harbor Push with Crane ==="
        
        # DNS設定でharbor.local解決を有効化
        echo "192.168.122.100 harbor.local" | sudo tee -a /etc/hosts
        
        # Craneツールインストール
        curl -sL "https://github.com/google/go-containerregistry/releases/latest/download/go-containerregistry_Linux_x86_64.tar.gz" | tar xz -C /tmp
        chmod +x /tmp/crane
        
        # Docker login（明示的な認証）
        echo "Docker login実行中..."
        echo $HARBOR_PASSWORD | docker login 192.168.122.100 -u $HARBOR_USERNAME --password-stdin
        
        # Crane認証（insecure registry対応）
        export CRANE_INSECURE=true
        echo "Crane認証 - Username: $HARBOR_USERNAME, Password: ${HARBOR_PASSWORD:0:5}..."
        /tmp/crane auth login 192.168.122.100 -u $HARBOR_USERNAME -p $HARBOR_PASSWORD --insecure
        
        # 認証確認
        echo "Docker config.json内容:"
        cat ~/.docker/config.json
        
        # Harbor catalog確認
        echo "Harbor catalog確認:"
        curl -k -u $HARBOR_USERNAME:$HARBOR_PASSWORD https://192.168.122.100/v2/_catalog
        
        # Docker pushでテスト
        echo "Docker pushでテスト中..."
        docker push 192.168.122.100/sandbox/${{ github.event.repository.name }}:latest || echo "Docker push失敗"
        
        # latestタグプッシュ（crane使用）
        echo "Crane pushでテスト中..."
        docker save 192.168.122.100/sandbox/${{ github.event.repository.name }}:latest -o /tmp/image-latest.tar
        /tmp/crane push /tmp/image-latest.tar 192.168.122.100/sandbox/${{ github.event.repository.name }}:latest --insecure
        
        # commitハッシュタグプッシュ
        docker save 192.168.122.100/sandbox/${{ github.event.repository.name }}:${{ github.sha }} -o /tmp/image-commit.tar
        /tmp/crane push /tmp/image-commit.tar 192.168.122.100/sandbox/${{ github.event.repository.name }}:${{ github.sha }} --insecure
        
        echo "✅ Harbor push completed successfully"
        
    - name: プッシュ結果確認
      run: |
        echo "=== Harbor Push Verification ==="
        
        # latestタグ確認
        curl -k -u $HARBOR_USERNAME:$HARBOR_PASSWORD https://192.168.122.100/v2/sandbox/${{ github.event.repository.name }}/tags/list
        
        # リポジトリ一覧確認
        curl -k -u $HARBOR_USERNAME:$HARBOR_PASSWORD "https://192.168.122.100/api/v2.0/projects/sandbox/repositories"
        
        echo "=== Deployment completed successfully ==="
