# GitHub Actions workflow for Harbor certificate test
# 証明書配布状況の確認と簡単なアプローチ

name: Harbor Certificate Simple Test

on:
  workflow_dispatch:

jobs:
  cert-test:
    runs-on: slack.rs-runners
    
    steps:
    - name: 証明書配布状況確認
      run: |
        echo "=== ホストの証明書配布状況確認 ==="
        
        # ホストの証明書ディレクトリを確認
        echo "Docker証明書ディレクトリ:"
        ls -la /etc/docker/certs.d/ || echo "/etc/docker/certs.d/ が存在しません"
        
        if [ -d "/etc/docker/certs.d/192.168.122.100" ]; then
          echo "Harbor証明書ディレクトリ内容:"
          ls -la /etc/docker/certs.d/192.168.122.100/
          
          if [ -f "/etc/docker/certs.d/192.168.122.100/ca.crt" ]; then
            echo "Harbor CA証明書が存在します"
            echo "証明書詳細:"
            openssl x509 -in /etc/docker/certs.d/192.168.122.100/ca.crt -text -noout | grep -A2 "Subject Alternative Name"
          else
            echo "Harbor CA証明書が存在しません"
          fi
        else
          echo "Harbor証明書ディレクトリが存在しません"
        fi
        
        echo "=== システム証明書ストア確認 ==="
        ls -la /usr/share/ca-certificates/ | grep harbor || echo "システムにHarbor証明書なし"
        
        echo "=== 簡単なHTTPS接続テスト ==="
        curl -I https://192.168.122.100/v2/ 2>&1 || echo "HTTPS接続失敗"
        
        echo "=== Docker動作確認 ==="
        docker --version
        docker info | grep -i "registry" || echo "Docker registry設定なし"