name: Harborへのビルドとプッシュ

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: slack-rs-runners 
    
    steps:
    - name: コードをチェックアウト
      uses: actions/checkout@v4
      
    - name: Harbor接続テスト
      run: |
        echo "=== Harbor Connection Test ==="
        curl -k -u admin:Harbor12345 https://192.168.122.100/v2/_catalog
        curl -k -u admin:Harbor12345 https://192.168.122.100/api/v2.0/projects | jq '.[] | select(.name=="sandbox")'
        
    - name: Docker設定とビルド
      run: |
        echo "=== Docker Setup ==="
        
        # Docker認証設定
        mkdir -p ~/.docker
        echo '{"auths":{"192.168.122.100":{"auth":"'$(echo -n 'admin:Harbor12345' | base64 -w 0)'"}}}' > ~/.docker/config.json
        
        # Dockerイメージビルド
        docker build -t 192.168.122.100/sandbox/${{ github.event.repository.name }}:latest .
        
        echo "=== Docker Info ==="
        docker info | grep -A 5 "Insecure Registries" || echo "No insecure registries shown"
        
    - name: Harbor Push
      run: |
        echo "=== Harbor Push Attempt ==="
        
        # 直接プッシュ試行
        docker push 192.168.122.100/sandbox/${{ github.event.repository.name }}:latest
        
    - name: プッシュ結果確認
      run: |
        echo "=== Push Result Verification ==="
        curl -k -u admin:Harbor12345 https://192.168.122.100/v2/sandbox/${{ github.event.repository.name }}/tags/list
        curl -k -u admin:Harbor12345 "https://192.168.122.100/api/v2.0/projects/sandbox/repositories"