name: Build and Push to Harbor

on:
  push:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: slack-rs-runners

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Harbor CA Certificate
        run: |
          # 作成したTLS証明書を使用
          sudo mkdir -p /etc/docker/certs.d/192.168.122.100
          # 証明書をコピー (事前にrunnerホストにコピーしておく)
          sudo cp /home/runner/harbor.crt /etc/docker/certs.d/192.168.122.100/ca.crt
          
          # または、kubectlが利用可能な場合はsecretから取得
          # kubectl get secret harbor-tls-secret -n harbor -o jsonpath='{.data.tls\.crt}' | base64 -d > harbor.crt
          # sudo cp harbor.crt /etc/docker/certs.d/192.168.122.100/ca.crt

      - name: Login to Harbor with CA Certificate
        run: |
          echo "Harbor12345" | docker login 192.168.122.100 -u admin --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t 192.168.122.100/sandbox/slack-rs:latest .
          docker push 192.168.122.100/sandbox/slack-rs:latest