name: Docker Image CI

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Push to Docker Hub
        run: |
          curl -sk https://workflow.qroksera.com/api/v1/events/argoworkflow/workflow -H "Authorization: ${{ secrets.TOKEN }}" -d  '{"message": "slack.rs"}'