name: Build and Push to Harbor

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: slack-rs-runners  # ← Runner Scale Set名に変更

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup Docker for insecure registry
        run: |
          mkdir -p ~/.docker

          cat > ~/.docker/config.json <<EOF
          {
            "auths": {},
            "HttpHeaders": {
              "User-Agent": "Docker-Client/19.03.12 (linux)"
            },
            "credsStore": "",
            "experimental": "disabled",
            "stackOrchestrator": "swarm"
          }
          EOF

          echo '{
            "insecure-registries" : ["192.168.122.100"]
          }' | sudo tee /etc/docker/daemon.json

          sudo systemctl restart docker

      - name: Login to Harbor (insecure)
        run: |
          echo "Harbor12345" | docker login 192.168.122.100 -u admin --password-stdin

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: 192.168.122.100/sandbox/${{ github.event.repository.name }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
