name: Harborへのビルドとプッシュ

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: slack-rs-runners 
    
    steps:
    - name: コードをチェックアウト
      uses: actions/checkout@v4
      
    - name: Harbor接続テスト
      run: |
        echo "=== Harbor Connection Test ==="
        curl -k -u admin:Harbor12345 https://192.168.122.100/v2/_catalog
        curl -k -u admin:Harbor12345 https://192.168.122.100/api/v2.0/projects | jq '.[] | select(.name=="sandbox")'
        
    - name: Docker設定とビルド
      run: |
        echo "=== Docker Setup ==="
        
        # Docker認証設定
        mkdir -p ~/.docker
        echo '{"auths":{"192.168.122.100":{"auth":"'$(echo -n 'admin:Harbor12345' | base64 -w 0)'"}}}' > ~/.docker/config.json
        
        # Dockerイメージビルド
        docker build -t 192.168.122.100/sandbox/${{ github.event.repository.name }}:latest .
        
        echo "=== Docker Info ==="
        docker info | grep -A 5 "Insecure Registries" || echo "No insecure registries shown"
        
    - name: Harbor Push
      run: |
        echo "=== Harbor Push Attempt ==="
        
        # 方式1: 標準プッシュ試行
        docker push 192.168.122.100/sandbox/${{ github.event.repository.name }}:latest || echo "Standard push failed"
        
        # 方式2: craneツールを使用
        echo "Installing crane for insecure push..."
        curl -sL "https://github.com/google/go-containerregistry/releases/latest/download/go-containerregistry_Linux_x86_64.tar.gz" | tar xz -C /tmp
        chmod +x /tmp/crane
        
        echo "Using crane for insecure push..."
        /tmp/crane auth login 192.168.122.100 -u admin -p Harbor12345 --insecure || echo "Crane auth failed"
        /tmp/crane push 192.168.122.100/sandbox/${{ github.event.repository.name }}:latest --insecure || echo "Crane push failed"
        
        # 方式3: Docker save/load + curl upload
        echo "Manual upload attempt..."
        docker save 192.168.122.100/sandbox/${{ github.event.repository.name }}:latest | gzip > /tmp/image.tar.gz
        echo "Image saved to /tmp/image.tar.gz"
        
    - name: プッシュ結果確認
      run: |
        echo "=== Push Result Verification ==="
        curl -k -u admin:Harbor12345 https://192.168.122.100/v2/sandbox/${{ github.event.repository.name }}/tags/list
        curl -k -u admin:Harbor12345 "https://192.168.122.100/api/v2.0/projects/sandbox/repositories"