name: Build and Push to Harbor

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: slack-rs-runners

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx with insecure registry
        uses: docker/setup-buildx-action@v3
        with:
          config-inline: |
            [registry."192.168.122.100"]
              http = true
              insecure = true

      - name: Login to Harbor (HTTP)
        uses: docker/login-action@v3
        with:
          registry: 192.168.122.100
          username: admin
          password: Harbor12345
        env:
          DOCKER_REGISTRY_HTTP: "true"

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: 192.168.122.100/sandbox/slack-rs
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
